server:
  port: 8088

spring:
  application:
    name: ms-notificaciones
  rabbitmq:
    host: sanos_y_salvos_rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true