server:
  port: 8084

spring:
  application:
    name: ms-geolocalizacion
  data:
    redis:
      host: sanos_y_salvos_redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true